name: FTP Deploy

on:
  push:
    branches:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:    ${{ a2ea9.netcup.net }}
          username:  ${{ ftp_paderta	}}
          password:  ${{ jn59E_1d }}
          local-dir: ./dist/datengraf # Dein lokaler Build-Ordner
          server-dir: ./code.nozilla.net/httpdocs/datengraf # Dein Zielordner auf dem Server
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            DOCS.md
            SECURITY.md
            CONTRIBUTING.md
 

